### ISSUE TITLE
Add local time to every line with ms

### ISSUE THREAD

**Issue by taublast** [nertilpoci/VisualStudio-Output-Filter-Extension#16]
Thank you for this awesome tool!
Would be cool to add local time (including ms) to every filtered line so we can track when this did happen.
Thanks again!

**Comment by nertilpoci** [comment]
@taublast will try to do this but might not be possible. Because the window on the filter extension reads from output window. And output window itself doesn't have that information.

consider this case
You have a bunch of messages on the output window.
Then you open the filtereredoutputwindow(the extension one). At that point the extension will read the whole output window content and process that which would make all that preexisting content the same time as they would be processed later.

For new content it could work though since that would be processed as soon as it comes in so i could stamp it

**Comment by taublast** [comment]
Thanks! =)
